### ISSUE TITLE
Read correction error. Nanopore

### ISSUE THREAD

**Issue by timyerg** [dbeisser/Natrix2#4]
That is me again, unfortunately, with a new issue.

I am running Nanopore 16S data. My reads are already assembled, and primers removed. As advised [here](https://github.com/dbeisser/Natrix2/issues/3#issue-2153735302), I switched to dev repo and disabled the pychopper.

After running for a while, an error was encountered. I thought that it may be caused by RAM and increased it from 120 to 256, however, after relaunching the same project the same error arised.

```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 12
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	167	cd_hit
	171	cdhit
	1	clust_merge_results_vsearch
	171	cluster_sorting
	171	counts_minimap
	167	fastqc
	1	filtering
	1	generate_otu_fasta
	171	medaka_polishing
	1	merge_mumu_mothur_output
	1	merge_output
	170	minimap_align
	170	minimap_align_2
	171	minimap_align_3
	171	minimap_align_4
	171	minimap_medaka
	1	mothur_classify
	1	multiqc
	170	racon_polishing
	171	racon_polishing_2
	171	racon_polishing_3
	171	racon_polishing_4
	1	run_mumu
	1	unfiltered_table
	171	vsearch_chim
	1	vsearch_clust
	1	vsearch_header
	1	vsearch_otu
	1	write_clusters_uc
	1	write_fasta
	2740
Select jobs to execute...

[Mon Feb 26 17:41:15 2024]
rule racon_polishing_2:
    input: Nanopore_results/fasta/C03F3_A_R1.fasta, Nanopore_results/read_correction/minimap/C03F3_A_R1_align_2.sam, Nanopore_results/read_correction/racon/C03F3_A_R1_racon_1.fasta
    output: Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.tmp, Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.fasta
    jobid: 385
    wildcards: sample=C03F3, unit=A
    threads: 12

Activating conda environment: /Natrix2/.snakemake/conda/09de290b
[racon::Polisher::initialize] loaded target sequences 0.002148 s
[racon::Polisher::initialize] error: duplicate sequence 50b42c65-75ef-48f3-928f-6e5bb26b4741 with unequal data
[Mon Feb 26 17:41:19 2024]
Error in rule racon_polishing_2:
    jobid: 385
    output: Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.tmp, Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.fasta
    conda-env: /Natrix2/.snakemake/conda/09de290b
    shell:
        
                    racon  -m 8 -x -6 -g -8 -w 500 -t 12 Nanopore_results/fasta/C03F3_A_R1.fasta Nanopore_results/read_correction/minimap/C03F3_A_R1_align_2.sam Nanopore_results/read_correction/racon/C03F3_A_R1_racon_1.fasta > Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.tmp;
                    sed "s/[>].*[^|]|/>/" Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.tmp > Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.fasta
                
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job racon_polishing_2 since they might be corrupted:
Nanopore_results/read_correction/racon/C03F3_A_R1_racon_2.tmp
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Natrix2/.snakemake/log/2024-02-26T174111.290794.snakemake.log
```

As discussed [here](https://github.com/isovic/racon/issues/97#issue-381139914), the issue is related to duplicate IDs, but I don't know how to fix it here.

I hope that it is OK that I created two issues in one day.

**Comment by timyerg** [comment]
I think that I fixed the issue by modifying the rules. I will wait and see how far I will get this time.
Can I fork the repo and pull changes? Or I can put the modified file here when I will make sure that all fixes are working as intended.

**Comment by adeep619** [comment]
Hi there, 

We tested the changes on our dataset and they are working well. Could you please provide us with some additional information about your headers and base caller data? This will help us determine if the issue is specific to your dataset. Additionally, could you please share the details of the changes you have made?

Thank you,
Aman

**Comment by timyerg** [comment]
That means I am lucky to have a dataset that can cause some issues! As always =).
I added one line to each iteration that renames IDs in the racon output since the error was caused by the same IDs in fasta files and racon outputs.

```
            shell:
                """
                    racon  -m 8 -x -6 -g -8 -w 500 -t {threads} {input[0]} {input[1]} {input[2]} > {output.tmp};
                    sed -i -e 's/>/>polished3/g' {output.tmp};
                    sed 's/[>].*[^|]|/>' {output.tmp} > {output.final}
                """
```


After fixing it like this some samples already progressed to medaka with following IDs:

`>polished4polished3polished2polished18fc9f2bb-eb3f-4eef-954b-4b25ba6535bb`

From the person whos dataset I am working with I got following info:

> primers and adapters are already trimmed and the only quality-based filtering performed was in the minion during base calling in HAC (high-accuracy) mode (kept nanopore reads with Q > 8).

After receiving the files, I run chopper:

`gunzip -c $gz | chopper -q 10 -l 1200 --threads {THREADS} | gzip > $CR/$file`

Here is an example from original fastq file I got:

```
@db01deda-dc12-4612-af5e-c2a00ac9193d runid=d16a83d0f3e4f48e46f5ca136bf647f57d0f5927 sampleid=no_sample read=26672 ch=425 start_time=2023-06-07T11:21:32Z model_version_id=2021-05-17_dna_r9.4.1_minion_384_d37a2ab9 barcode=barcode06
GATGAACGCCGGCGGTGTGCTAATACATGCAAGTCGAACGCGTTGGCCCAATTGATTGATGGTGCTTTACCTGATTGATTTTTGGTCGCCAGCGAAGGTGGCGGACGGGTGGTAACACGTAGATGGCCCTGCCCAGAAGCGGGGGACAACATTTGGAAACAGATGCTAATACCGCATAACAGCGTTGTTCGCATGAACAACGCTTCTGCTTCTCGCTATCACTTCTGGATGGACCTGCGGTCATTAGCTTGTTGGTGGGGTAACGGCCTACCAAGGCGATGATGCATAGCCGAGTTGAAAACTGATCGGCCACAATGGGACTGAGACACGGCCCATACTCCTACGGGAGGCAGCAGTAGGGAATCTTCTACAATGGGCGCAAGCCTGATGAACAACACCGCGTGAGTGAAGAAGGTTTTCGGCTCGTAAAGCTCTGTTGTTAAAGAAGAACACGTATAGAGTAACTGTTCATACGTTGACGGTATTTAACCAGAAAGTCACGGCTAACTACGTGCCAGCAGCCGCGGTAATACGTAGGTGGCTTACTTATCCGGATTTATTGGGCGTAAAGAGAGTGCAGGCGGTTTTCTAAGTCTGATGAAAAGCCTTCGGTAACCGGAGAAGTGCATCGGAAACTGGATAACTTGAGTGCAGAAGGGTAAATTGGAACTCCATGTGTAGCGGTGGAATGCGTAGATATATATGGAAGAACACCAGTGGCGAAGGCAACGGCTACCTGGTCTGCAACTGACGCTGAGACTCAACATGGAGTAGCGAACAGGATTAGATACCCCTGTCCATGCCGTAAACGATGAGTGCTAGGTGTTGGAGGTTTCCGCCCTTCAGTGCCGGGCTAACGCATTCGCCTCCGCCTGGGGGTACGACTGCAAGTTCAAACTCCAAAGAAGAGATTCGACGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGAAGCTACGCGAAAAAGTGCCCGCCTGACATCTTGCGCAGCAGAGATGGGGCGTTTCAGGAACGCGCAATGACGGTGGTGCATGGTCGTCGTCAGCTCGTGTCGTGAGATGTTGGGTTAAGTCCCGCAGCAGCACAACCCTTGTTACTAGTTGCCAGCATTAAGTTGGGCACTCTAGAGAGACCGCCGGTGACCGGAGGAAGGTGGGGATGACGTCAAGTCATCATGCCCCTTATGACCTGGGCTACACACGTGCTGCAATGGGCAGTACAACGAGAAGCGAACCCGCGAGGGTAGCGGATCTCTTAAAGCTGTTCTCAGTTCGGACTGCAGGCTGCAACTCGCCTGCACGAAGCTGGAATCGCTAGTAATCGCGGATCAGCACGCCGCGGTGAATACGTTCCCGGGCGCGCACACCGCCCCGTCACACCATGGAAGTCTGCAATGCCCAAAGTCGGTGGGATAACCTTTGCCGTCAATAGCCGCCTAAGGTAAGAATTGACTGGGGTG
+
-.@;:::8:97551111940+++)))*-255568:55667<;;=>>==<==;>@A@<)(&'(*+++/.144554435<<=9644434(''&(+((****''*,,13.)()**.012--,1/*&&&%*,(,--,),--000***078::-,,-<=>0-154447>?@<?>>?;;9;:9::>6,,,,<968:11//02?@<100/.'&&'))*,,-0/../37789<5598;;54435/600/(''40//,(&')*156>BA=>A=A??=:(((();>:;::::?/...99=<<9999:60-((((8;?;411++,.8;??A<5454676:569:767668==:<;259:854400--//.-20:9;987,***-<=>9966:54464720)''''23578<?<=<65579,/0+*))-17899:79--.../&&'+/122:C@B:</0+.,**,,9<<%$$'%(*+34>?>8888?<<=EA;::5443333?++*+///1(''.5443588;8843,,,,,,-002=7370/..(&%%&()(''''&&,-.70+-,-44@@A::9:>>><88/.-+,.9;;;<<?>;@;?32<.7<21//($$$$$%&')+'%$%(.1.01--)))))>>@//688679?A97.-*+,,-9:<;988**((+)'())*2456;7&&&%+-12433459;?<<@((&&%&)..1{3:=A<69854785429::7841.+(%%%&,-565585563347;??>?>==;9)((+36'&&''7:.-++888778/..-123::;0///5669=:6943304447:,++,,56:<;:869:99988:9);====<:2,+*))*/695500((/9<=222'&&%&'5.89:;654*%%()+-656/('%%'%%&(*+&')-10,)*('&'')*+-,-23:21324;956698:::8854***+<==<;:=<43532226''''-..++*028,.0-+,/24455A=<11../'&&*')*,,34546..-+,,:97726886899(&&&'13677<=>><;:338456790.-+*('()+12=@??=:::<42423,,--**(''*../01***76967+)))*&&%%%%&56641444><<---0;444{858114::78800.((.48235646978:;<98///>0/58<787,,++)(()))*0212'322397768{:34;;:+**,8::=>=<>>?;333..-,/4+*))*06>=>>:0//''225;<9;{D4434525677..,..6:><<;;;9:9:<<;<A:::9;<<<>>::22--/-----,6<>:999=<=@46867;><6667;=?3?<:998520001336500/0*+-)'&))/+632048=33-,,((((-232:0((('9><><??,.:><66669=>==79775*))$$$&()))-05:;:<0,,..*'&$%&'),+,//100
```

I attached a modified file.

[read_correction.zip](https://github.com/dbeisser/Natrix2/files/14420001/read_correction.zip)

**Comment by timyerg** [comment]
hi, me again.
A new error was encountered. Is it related to renamed IDs or should I create a new issue?

```
Select jobs to execute...
/Natrix2/.snakemake/conda/471aeff1/lib/python3.6/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/Natrix2/.snakemake/conda/471aeff1/lib/python3.6/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
Traceback (most recent call last):
  File "/Natrix2/.snakemake/conda/471aeff1/bin/multiqc", line 766, in <module>
    multiqc()
  File "/Natrix2/.snakemake/conda/471aeff1/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Natrix2/.snakemake/conda/471aeff1/lib/python3.6/site-packages/click/core.py", line 1034, in main
    _verify_python_env()
  File "Natrix2/.snakemake/conda/471aeff1/lib/python3.6/site-packages/click/_unicodefun.py", line 100, in _verify_python_env
    raise RuntimeError("\n\n".join(extra))
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system lists some UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: aa_DJ.utf8, aa_ER.utf8, aa_ET.utf8, af_ZA.utf8, am_ET.utf8, an_ES.utf8, ar_AE.utf8, ar_BH.utf8, ar_DZ.utf8, ar_EG.utf8, ar_IN.utf8, ar_IQ.utf8, ar_JO.utf8, ar_KW.utf8, ar_LB.utf8, ar_LY.utf8, ar_MA.utf8, ar_OM.utf8, ar_QA.utf8, ar_SA.utf8, ar_SD.utf8, ar_SY.utf8, ar_TN.utf8, ar_YE.utf8, as_IN.utf8, ast_ES.utf8, ayc_PE.utf8, az_AZ.utf8, be_BY.utf8, bem_ZM.utf8, ber_DZ.utf8, ber_MA.utf8, bg_BG.utf8, bho_IN.utf8, bn_BD.utf8, bn_IN.utf8, bo_CN.utf8, bo_IN.utf8, br_FR.utf8, brx_IN.utf8, bs_BA.utf8, byn_ER.utf8, ca_AD.utf8, ca_ES.utf8, ca_FR.utf8, ca_IT.utf8, crh_UA.utf8, cs_CZ.utf8, csb_PL.utf8, cv_RU.utf8, cy_GB.utf8, da_DK.utf8, de_AT.utf8, de_BE.utf8, de_CH.utf8, de_DE.utf8, de_LU.utf8, doi_IN.utf8, dv_MV.utf8, dz_BT.utf8, el_CY.utf8, el_GR.utf8, en_AG.utf8, en_AU.utf8, en_BW.utf8, en_CA.utf8, en_DK.utf8, en_GB.utf8, en_HK.utf8, en_IE.utf8, en_IN.utf8, en_NG.utf8, en_NZ.utf8, en_PH.utf8, en_SG.utf8, en_US.utf8, en_ZA.utf8, en_ZM.utf8, en_ZW.utf8, es_AR.utf8, es_BO.utf8, es_CL.utf8, es_CO.utf8, es_CR.utf8, es_CU.utf8, es_DO.utf8, es_EC.utf8, es_ES.utf8, es_GT.utf8, es_HN.utf8, es_MX.utf8, es_NI.utf8, es_PA.utf8, es_PE.utf8, es_PR.utf8, es_PY.utf8, es_SV.utf8, es_US.utf8, es_UY.utf8, es_VE.utf8, et_EE.utf8, eu_ES.utf8, fa_IR.utf8, ff_SN.utf8, fi_FI.utf8, fil_PH.utf8, fo_FO.utf8, fr_BE.utf8, fr_CA.utf8, fr_CH.utf8, fr_FR.utf8, fr_LU.utf8, fur_IT.utf8, fy_DE.utf8, fy_NL.utf8, ga_IE.utf8, gd_GB.utf8, gez_ER.utf8, gez_ET.utf8, gl_ES.utf8, gu_IN.utf8, gv_GB.utf8, ha_NG.utf8, he_IL.utf8, hi_IN.utf8, hne_IN.utf8, hr_HR.utf8, hsb_DE.utf8, ht_HT.utf8, hu_HU.utf8, hy_AM.utf8, ia_FR.utf8, id_ID.utf8, ig_NG.utf8, ik_CA.utf8, is_IS.utf8, it_CH.utf8, it_IT.utf8, iu_CA.utf8, iw_IL.utf8, ja_JP.utf8, ka_GE.utf8, kk_KZ.utf8, kl_GL.utf8, km_KH.utf8, kn_IN.utf8, ko_KR.utf8, kok_IN.utf8, ks_IN.utf8, ku_TR.utf8, kw_GB.utf8, ky_KG.utf8, lb_LU.utf8, lg_UG.utf8, li_BE.utf8, li_NL.utf8, lij_IT.utf8, lo_LA.utf8, lt_LT.utf8, lv_LV.utf8, mag_IN.utf8, mai_IN.utf8, mg_MG.utf8, mhr_RU.utf8, mi_NZ.utf8, mk_MK.utf8, ml_IN.utf8, mn_MN.utf8, mni_IN.utf8, mr_IN.utf8, ms_MY.utf8, mt_MT.utf8, my_MM.utf8, nb_NO.utf8, nds_DE.utf8, nds_NL.utf8, ne_NP.utf8, nhn_MX.utf8, niu_NU.utf8, niu_NZ.utf8, nl_AW.utf8, nl_BE.utf8, nl_NL.utf8, nn_NO.utf8, nr_ZA.utf8, nso_ZA.utf8, oc_FR.utf8, om_ET.utf8, om_KE.utf8, or_IN.utf8, os_RU.utf8, pa_IN.utf8, pa_PK.utf8, pap_AN.utf8, pl_PL.utf8, ps_AF.utf8, pt_BR.utf8, pt_PT.utf8, ro_RO.utf8, ru_RU.utf8, ru_UA.utf8, rw_RW.utf8, sa_IN.utf8, sat_IN.utf8, sc_IT.utf8, sd_IN.utf8, se_NO.utf8, shs_CA.utf8, si_LK.utf8, sid_ET.utf8, sk_SK.utf8, sl_SI.utf8, so_DJ.utf8, so_ET.utf8, so_KE.utf8, so_SO.utf8, sq_AL.utf8, sq_MK.utf8, sr_ME.utf8, sr_RS.utf8, ss_ZA.utf8, st_ZA.utf8, sv_FI.utf8, sv_SE.utf8, sw_KE.utf8, sw_TZ.utf8, szl_PL.utf8, ta_IN.utf8, ta_LK.utf8, te_IN.utf8, tg_TJ.utf8, th_TH.utf8, ti_ER.utf8, ti_ET.utf8, tig_ER.utf8, tk_TM.utf8, tl_PH.utf8, tn_ZA.utf8, tr_CY.utf8, tr_TR.utf8, ts_ZA.utf8, tt_RU.utf8, ug_CN.utf8, uk_UA.utf8, unm_US.utf8, ur_IN.utf8, ur_PK.utf8, ve_ZA.utf8, vi_VN.utf8, wa_BE.utf8, wae_CH.utf8, wal_ET.utf8, wo_SN.utf8, xh_ZA.utf8, yi_US.utf8, yo_NG.utf8, yue_HK.utf8, zh_CN.utf8, zh_HK.utf8, zh_SG.utf8, zh_TW.utf8, zu_ZA.utf8
[Fri Mar  1 02:14:53 2024]
Error in rule multiqc:
    jobid: 1
    output: Nanopore_results/qc/multiqc_report.html
    conda-env: /Natrix2/.snakemake/conda/471aeff1
    shell:
        multiqc Nanopore_results/qc/ -o Nanopore_results/qc/
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Fri Mar  1 02:15:28 2024]
Finished job 807.
2962 of 3264 steps (91%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: Natrix2/.snakemake/log/2024-02-27T122043.508326.snakemake.log
```

**Comment by timyerg** [comment]
Thank you again for the tool. I like the output after Mumu reclustering.
The run was completed successfully. Renaming IDs to solve this issue did not affect other steps. 
The only thing is that taxonomy (Silva with Mothur) was not added to the final outputs. I checked if renamed IDs are involved, but as far as I can see, they are not already involved at this step. So I am not sure what the reason is. It is unimportant for me since I planned to reclassify it outside the Natrix2 anyway.
Closing the issue.

Best,

**Comment by adeep619** [comment]
Hi there,
Thank you so much for your comments. we have resolved the issues for taxonomy in the final output and will push changes soon to the main pipeline. Your feedback helps us improve our service, so thank you for sharing it with us.

**Comment by timyerg** [comment]
Glad to help! One more question - I read the paper but did not find the answer - do you think species level annotations for 16S long nanopore reads are possible or it is better to work at genus level only (even if species were annotated)?

**Comment by DanaBlu** [comment]
Hello,

If you're considering taxonomic classification with mothur, I would advise against working at the species level. Mothur itself discourages this practice, as outlined on its official webpage (https://mothur.org/wiki/classify.seqs/#common-questions).

_"**How do you recommend classifying to the species level?** Unfortunately I do not. You will never get species level classification if you are using the RDP or Silva references. They only go to the genus level. Even the greengenes database only has 10% or so of sequences with species level names (greengenes hasn’t been updated in quite a few years). I and many others would contend that using 16S and especially a fragment to get a species name is asking too much - you need a culture and genome sequencing to do that. If someone wanted to give it a shot, they would need to add the species level names to the taxonomy strings. Also, they would need to add many more sequences that represent each species. Outside of a few groups of bacteria where the researchers have carefully selected the region (e.g. Lactobacillus or Staphylococcus), I really think this would be a lot of work for little/no benefit."_

If your objective is to work at the species level, an alternative approach could be to employ taxonomic classification via blast, setting the 'ident' parameter to your desired minimal identity overlap between the target and query sequences. This threshold can be customized in the [https://github.com/dbeisser/Natrix2/blob/dev/Nanopore.yaml](url) file's options.

Feel free to reach out if you have any further questions!

Best,
Dana

**Comment by timyerg** [comment]
Thank you for detailed reply. I expected it, but decided to ask here in case of miracle.

Best,
Timur
